### PR TITLE
found a few spelling mistakes

### PR DESCRIPTION
**Pull request by kenman345**
Just helping out when I saw a mistake.

Also, saw you were not mentioning the travis yaml file appropriately. It technically is supposed to have a period at the front.

### CODE REVIEW

**Comment by bluzi** [comment]
Thanks @kenman345, as you've probably already noticed, the tests in this repo are currently broken, so you can ignore what @TravisBuddy is posting here.

Anyway, thanks! I'm merging your changes.

**Comment by kenman345** [comment]
Notew, the merged commit did not fail the tests because it was your user account merging and it is from your repo that the tests were run.

**Comment by bluzi** [comment]
Hey, I'm aware of that, thanks!

**Comment by kenman345** [comment]
I think you mean that you didnt know that. But yea, I believe thats what happened in this case.

**Pull request merged**
